# Generated by Django 6.1.1 on 2026-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_interview_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
