# Generated by Django 6.1.1 on 2026-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_ai_interview_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_recommendation',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
