# Generated by Django 6.1.1 on 2026-10-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_assessment_assessmentattempt_assessmentquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='assessmentattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assessment Attempt', 'verbose_name_plural': 'Assessment Attempts'},
        ),
        migrations.AlterModelOptions(
            name='assessmentquestion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Assessment Question', 'verbose_name_plural': 'Assessment Questions'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-interview_time'], 'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AlterModelOptions(
            name='interviewfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interview Feedback', 'verbose_name_plural': 'Interview Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='savedjob',
            options={'ordering': ['-saved_at'], 'verbose_name': 'Saved Job', 'verbose_name_plural': 'Saved Jobs'},
        ),
        migrations.AlterModelOptions(
            name='statushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Status History', 'verbose_name_plural': 'Status Histories'},
        ),
    ]
