# Generated by Django 6.1.1 on 2026-10-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='recruiterprofile',
            options={'verbose_name': 'Recruiter Profile', 'verbose_name_plural': 'Recruiter Profiles'},
        ),
    ]
